export const audits = [
  {
    id: "AUD-2025-0047",
    product: "Sparkle Hydration Energy Drink",
    sku: "SHD-750-IND",
    category: "Food & Beverage",
    source: "Field capture",
    inspector: "AAnubhav Pandey",
    capturedAt: "2025-06-18T10:42:00",
    location: "Pune, Maharashtra",
    score: 45,
    status: "Violation",
    violations: 4,
    image: "can",
    hash: "sha256:4d61…a8c2",
    batch: "SHD-VN-2405",
    originListing: "India",
    originPack: "Vietnam",
    mrp: "₹125.00",
    quantity: "750 ml",
    usp: "Not declared",
    evidenceTier: "Tier 1 · Field",
  },
  {
    id: "AUD-2025-0046",
    product: "NaturaGlow Aloe Face Wash",
    sku: "NGF-150-01",
    category: "Cosmetics",
    source: "Marketplace scan",
    inspector: "R. Iyer",
    capturedAt: "2025-06-17T15:18:00",
    location: "Mumbai, Maharashtra",
    score: 78,
    status: "Needs review",
    violations: 2,
    image: "tube",
    hash: "sha256:71b2…c911",
    batch: "NG-0525",
    originListing: "India",
    originPack: "India",
    mrp: "₹299.00",
    quantity: "150 ml",
    usp: "Declared",
    evidenceTier: "Tier 2 · Marketplace",
  },
  {
    id: "AUD-2025-0045",
    product: "Kaveri Basmati Rice",
    sku: "KBR-5K-2025",
    category: "Food & Beverage",
    source: "Batch catalog",
    inspector: "Devendra Singh",
    capturedAt: "2025-06-17T11:06:00",
    location: "Nashik, Maharashtra",
    score: 92,
    status: "Compliant",
    violations: 0,
    image: "rice",
    hash: "sha256:bc20…e2a0",
    batch: "KB-0625",
    originListing: "India",
    originPack: "India",
    mrp: "₹640.00",
    quantity: "5 kg",
    usp: "₹128/kg",
    evidenceTier: "Tier 3 · Catalog",
  },
  {
    id: "AUD-2025-0044",
    product: "HomePro Stainless Flask",
    sku: "HPF-1000-SS",
    category: "Household",
    source: "Field capture",
    inspector: "Asha Kulkarni",
    capturedAt: "2025-06-16T09:31:00",
    location: "Satara, Maharashtra",
    score: 64,
    status: "Violation",
    violations: 3,
    image: "flask",
    hash: "sha256:f09a…12de",
    batch: "HP-APR25",
    originListing: "India",
    originPack: "India",
    mrp: "₹899.00",
    quantity: "1 unit",
    usp: "Not declared",
    evidenceTier: "Tier 1 · Field",
  },
  {
    id: "AUD-2025-0043",
    product: "Veda Herbal Hair Oil",
    sku: "VHO-200-09",
    category: "Personal care",
    source: "Marketplace scan",
    inspector: "N. Thomas",
    capturedAt: "2025-06-15T16:23:00",
    location: "Nagpur, Maharashtra",
    score: 86,
    status: "Compliant",
    violations: 1,
    image: "bottle",
    hash: "sha256:0ab4…7cd1",
    batch: "VH-0525",
    originListing: "India",
    originPack: "India",
    mrp: "₹210.00",
    quantity: "200 ml",
    usp: "₹1.05/ml",
    evidenceTier: "Tier 2 · Marketplace",
  },
];

export const violations = [
  {
    rule: "Rule 6(1)(g) read with Rule 6(11)",
    severity: "Major",
    requirement: "Unit sale price must be declared for packaged commodities.",
    finding: "No unit sale price visible on the principal display panel. Expected ₹0.17/ml.",
    status: "Violation",
    deduction: "-20",
  },
  {
    rule: "Rule 6(10)",
    severity: "Critical",
    requirement: "Country of origin on pack must correspond to listing declaration.",
    finding: "Marketplace listing states India; pack OCR reads Product of Vietnam.",
    status: "Violation",
    deduction: "-35",
  },
  {
    rule: "Rule 13",
    severity: "Major",
    requirement: "Net quantity must use a statutory SI unit abbreviation.",
    finding: "The label uses “750 gms” in the nutrition declaration rather than “750 g”.",
    status: "Violation",
    deduction: "-20",
  },
  {
    rule: "Schedule II, Table I",
    severity: "Compliant",
    requirement: "Mandatory declaration text must meet minimum font height.",
    finding: "Measured at 2.1 mm; minimum for this quantity band is 2.0 mm.",
    status: "Compliant",
    deduction: "0",
  },
];

export const evidence = [
  { id: "EV-0047-01", auditId: "AUD-2025-0047", label: "Front panel · annotated", source: "Field capture", capturedAt: "18 Jun 2025 · 10:42", location: "Pune, Maharashtra", flag: "Violation", image: "can" },
  { id: "EV-0047-02", auditId: "AUD-2025-0047", label: "Origin statement", source: "Field capture", capturedAt: "18 Jun 2025 · 10:43", location: "Pune, Maharashtra", flag: "Violation", image: "origin" },
  { id: "EV-0047-03", auditId: "AUD-2025-0047", label: "Marketplace listing", source: "Marketplace", capturedAt: "18 Jun 2025 · 10:44", location: "QuickBite · Pune", flag: "Mismatch", image: "listing" },
  { id: "EV-0045-01", auditId: "AUD-2025-0045", label: "Bag front panel", source: "Batch catalog", capturedAt: "17 Jun 2025 · 11:06", location: "Nashik, Maharashtra", flag: "Clear", image: "rice" },
  { id: "EV-0044-01", auditId: "AUD-2025-0044", label: "Capacity marking", source: "Field capture", capturedAt: "16 Jun 2025 · 09:31", location: "Satara, Maharashtra", flag: "Violation", image: "flask" },
  { id: "EV-0043-01", auditId: "AUD-2025-0043", label: "Back panel declarations", source: "Marketplace", capturedAt: "15 Jun 2025 · 16:23", location: "Nagpur, Maharashtra", flag: "Clear", image: "bottle" },
];

export const reports = [
  { id: "RPT-2025-0018", auditId: "AUD-2025-0047", reference: "LM/PUN/SCN/2025/018", issuedAt: "18 Jun 2025 · 11:04", respondent: "QuickBite Global Retail Pvt. Ltd.", product: "Sparkle Hydration Energy Drink", status: "Ready", score: 45 },
  { id: "RPT-2025-0017", auditId: "AUD-2025-0044", reference: "LM/SAT/SCN/2025/017", issuedAt: "16 Jun 2025 · 10:12", respondent: "HomePro Retail India", product: "HomePro Stainless Flask", status: "Draft", score: 64 },
];

export const featureGroups = [
  { title: "Rule engine", kicker: "Deterministic statutory checks", color: "blue", items: ["Rule 6(1)(a-h) declaration validator", "Rule 6(11) unit sale price arithmetic", "Rule 7 / Schedule II font-height checks", "SI unit guardrails and category routing"] },
  { title: "Computer vision", kicker: "Spatial evidence, not black-box guesses", color: "ochre", items: ["Cylindrical panoramic stitching", "Multilingual PaddleOCR with bounding boxes", "Reference-calibrated PDP dimensions", "Glare removal, deskew and image quality gate"] },
  { title: "Fraud & integrity", kicker: "Find the disconnects", color: "red", items: ["Listing versus pack origin mismatch", "Price and quantity disconnect", "Immutable SHA-256 evidence chain", "Rule 27 registration lookup"] },
  { title: "Tracking & security", kicker: "A defensible audit trail", color: "slate", items: ["Role-based access for officers and regulators", "Append-only audit store", "Evidence tiering and retention controls", "Offline sync queue for field work"] },
  { title: "Ingestion", kicker: "Meet evidence where it exists", color: "green", items: ["Mobile field capture and video sweep", "Marketplace crawler for five sources", "Batch CSV / JSON catalog processor", "Offline OCR readiness indicators"] },
  { title: "Enforcement", kicker: "Turn a finding into an action", color: "plum", items: ["Section 15 / Rule 32 Show Cause Notice", "One-click report generation", "Print-ready statutory layout", "Digital verification footer"] },
  { title: "Analytics", kicker: "See patterns across the register", color: "blue", items: ["Compliance trend by period", "Category error rates and severity", "Repeat-offender and batch escalation", "Geographic hotspot review"] },
];

export const navItems = [
  { href: "/", label: "Overview", icon: "LayoutDashboard" },
  { href: "/scan", label: "Live Scanner", icon: "Camera" },
  { href: "/audits", label: "Audit register", icon: "ClipboardList" },
  { href: "/evidence", label: "Evidence", icon: "Image" },
  { href: "/reports", label: "Reports", icon: "FileText" },
  { href: "/analytics", label: "Analytics", icon: "ChartNoAxesCombined" },
];
